### ISSUE TITLE
Usuń exit(1)

### ISSUE THREAD

**Issue by julian-bednarek** [H8sGR8/OOPC#1]
https://github.com/H8sGR8/OOPC/blob/3f319448cd5dbbcb7ad82940a2f784d4806798a4/stack_c%2B%2B/stack.cpp#L17

Bo teraz twój destruktow jest zjebany

**Comment by H8sGR8** [comment]
ale ma wyrzucac program

**Comment by H8sGR8** [comment]
jednak trzeba

**Comment by julian-bednarek** [comment]
głupoty, głupoty
