### ISSUE TITLE
CZY TY WIESZ CO TO ENKAPSULACJA

### ISSUE THREAD

**Issue by julian-bednarek** [H8sGR8/OOPC#2]
https://github.com/H8sGR8/OOPC/blob/3f319448cd5dbbcb7ad82940a2f784d4806798a4/stack_c%2B%2B/stack.h#L7

tak samo z top

**Comment by H8sGR8** [comment]
to akurat mozna zmienic

**Comment by H8sGR8** [comment]
to jest wersja robocza
