### ISSUE TITLE
CO TO JEST

### ISSUE THREAD

**Issue by julian-bednarek** [H8sGR8/OOPC#3]
https://github.com/H8sGR8/OOPC/blob/3f319448cd5dbbcb7ad82940a2f784d4806798a4/stack_c%2B%2B/stack.cpp#L25

CO TO KURWA JEST STARY, NAUCZ SIE C++

**Comment by julian-bednarek** [comment]
https://www.geeksforgeeks.org/delete-this-in-c/

**Comment by H8sGR8** [comment]
bo jestem goat

**Comment by julian-bednarek** [comment]
weź to napraw bo cie zje ziomeczek

**Comment by H8sGR8** [comment]
no ale to destructor wywoluje

**Comment by H8sGR8** [comment]
jest git

**Comment by julian-bednarek** [comment]
NIGDY NIE WYWOŁUJE SIĘ DESTRUKTORA
